version: "3"

services:
  prometheus_service:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana_service:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3756:3000"
    depends_on:
      - prometheus_service
