global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "node_export"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.2.46:9101"]

  - job_name: "clickhouse-test"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.2.46:3755"]
